### PR TITLE
Update polyhedron.sign() to comply with new python standard.

### PR DESCRIPTION
**Pull request by keileg**
I did a minor modification of the sign() function to make it work with new versions of python.

### CODE REVIEW

**Comment by mdickinson** [comment]
Thank you for the PR! It took me a few moments to understand what this fixes, but I think I figured it out: for Python `int` and `float` objects, I believe `(x > 0) - (x < 0)` does the right thing, but given a *NumPy* `float64`, we get the following:

```
>>> import numpy as np
>>> x = np.float64(13)
>>> x
13.0
>>> x > 0
True
>>> (x > 0) - (x < 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

(And that's because for a NumPy float `x`, `x > 0` has type `numpy.bool_` rather than regular Python `bool`.) @keileg: Can you confirm that this the error that you were encountering?

Alongside this change, it would be great to have a regression test in `test_polyhedron.py` that exercises this case. @keileg if you have the time and inclination to add such a test to your PR, it would be much appreciated. If not, that's fine too: I can do it, but probably won't have time before next weekend.

**Review by mdickinson — APPROVED** [review]
LGTM. Not only does this work correctly for NumPy `float64` instances; it's also cleaner, less hacky code than the original. As mentioned in comments, I'd quite like to add a regression test before merging this.

**Comment by mdickinson** [comment]
I've added a PR with regression tests in #3. Merging this PR. Thanks again for the contribution!

**Comment by keileg** [comment]
Sorry for the late reply, and thanks for the rapid fix! Do I understand you correctly that you do not need anything from me?

Also, thanks for making the code available, I found nothing else with comparable functionality, and I am very grateful not having to implement this myself.

**Comment by mdickinson** [comment]
> Do I understand you correctly that you do not need anything from me?

Sorry; yes. Apologies for the confusion. I decided that it was a choice between (a) applying the fix now, and (b) it falling off the bottom of the to-do list, so I went ahead and added the regression test.

**Comment by keileg** [comment]
Great. Once again, thanks for the rapid response!

**Pull request merged**
